spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xxxxxx:xxxx/winter?characterEncoding=UTF-8&useUnicode=true&serverTimezone=Asia/Shanghai
    username: xxxx
    password: xxxx
    type: com.zaxxer.hikari.HikariDataSource

  redis:
    host: xxxxxxx
    port: 6379
    database: 0
    password: xxxx